---
version: "3"

tasks:
  install:
    desc: Install the server
    cmds:
      - tasks: [compile]
      - mix ecto.create
      - mix ecto.migrate

  start:server:
    desc: Run the server
    cmds:
      - elixir --name derpy-coder@127.0.0.1 -S mix phx.server

  start:console:
    desc: Run iex in conjunction with the server
    summary: |
      Make sure the server is running.
      This is useful for running iex alongside server. Which means any PubSub events fired from iex is received by the server.
    cmds:
      - iex --name "console@127.0.0.1" --remsh "derpy-coder@127.0.0.1"

  start:iex:
    desc: Run iex standalone
    cmds:
      - PHX_SERVER=$PHX_SERVER iex -S mix
    env:
      PHX_SERVER: false

  reset:
    desc: Reset the database and its tables
    cmds:
      - mix ecto.reset

  analyze:credo:
    desc: Analyze code for consistency
    cmds:
      - cmd: mix credo
        ignore_error: true

  analyze:sobelow:
    desc: Analyze code for vulnerabilities
    cmds:
      - cmd: mix sobelow --compact
        ignore_error: true

  format:check:
    desc: Format code
    cmds:
      - mix format --check-formatted

  format:
    desc: Format code
    cmds:
      - mix format

  update:
    desc: Update all dependencies
    cmds:
      - mix deps.update --all
      - tasks: [compile]

  compile:
    desc: Fetch & Compile dependencies
    cmds:
      - mix do deps.get, deps.compile
