---
version: "3"

tasks:
  install:asdf:
    desc: Install asdf and related plugins using brew
    summary: |
      Type `asdf list all elixir` to list all versions of elixir and
      Type `asdf list elixir` to list only the version installed.
    cmds:
      - brew install asdf
      - asdf plugin-add mc https://github.com/penpyt/asdf-mc.git
      - asdf plugin add minio https://github.com/aeons/asdf-minio.git
      - asdf plugin-add caddy https://github.com/salasrod/asdf-caddy.git
      - asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
      - asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
      - asdf plugin-add mkcert https://github.com/salasrod/asdf-mkcert.git
      - asdf plugin-add cockroach https://github.com/salasrod/asdf-cockroach.git
  install:tools:
    desc: Install all tools with help of asdf
    summary: |
      It will pickup up versions from .tool-versions file and install them.

      To update all asdf plugins: `asdf plugin-update --all`
    cmds:
      - asdf install
      - brew install pgweb
      - brew install mkcert
      - brew install netdata
      - brew install varnish
      - brew install haproxy
      - brew install imgproxy
      - brew install meilisearch
      - brew install kevinburke/safe/hostsfile
      - mix  local.hex, local.phx, local.rebar
      - mix  escript.install hex livebook
      - asdf reshim elixir
  install:deps:
    desc: Fetch & Compile dependencies
    cmds:
      - mix do deps.get, deps.compile

  generate:caddy_cert:
    desc: Installs and Initiates the SSL Certificates
    summary: |
      We must rename whatever certificate file name gets generated to:
      ui.pem & ui-key.pem
    cmds:
      - mkcert -install
      - mkcert derpycoder derpycoder.site "*.derpycoder.site" localhost 127.0.0.1 ::1
      - mkdir -p certs/caddy
      - mv derpycoder+5.pem certs/caddy/cert.pem
      - mv derpycoder+5-key.pem certs/caddy/key.pem
  generate:cockroach_cert:
    desc: Generates all the certificates necessary to run a cockroach db cluster
    cmds:
      - cockroach cert create-ca
        --certs-dir=certs/cockroach_db
        --ca-key=keys/ca.key
      - cockroach cert create-node
        localhost
        cockroach.derpycoder.site
        --certs-dir=certs/cockroach_db
        --ca-key=keys/ca.key
      - cockroach cert create-client
        root
        --certs-dir=certs/cockroach_db
        --ca-key=keys/ca.key
      - cockroach cert create-client
        derp
        --certs-dir=certs/cockroach_db
        --ca-key=keys/ca.key
      - openssl pkcs8 -topk8 -inform PEM -outform DER
        -in certs/cockroach_db/client.derp.key
        -out certs/cockroach_db/client.derp.pk8
        -nocrypt
      - cockroach cert list
        --certs-dir=certs/cockroach_db
      - mkcert localhost cockroach.derpycoder.site
      - mkdir -p certs/cockroach_db
      - mv localhost+1.pem certs/cockroach_db/ui.crt
      - mv localhost+1-key.pem certs/cockroach_db/ui.key
  generate:minio_cert:
    desc: Generates the certificates necessary to run Minio
    cmds:
      - mkcert localhost minio.derpycoder.site s3.derpycoder.site
      - mkdir -p certs/minio
      - mv localhost+2.pem certs/minio/public.crt
      - mv localhost+2-key.pem certs/minio/private.key
  generate:meilisearch_cert:
    desc: Generates the certificates necessary to run Meilisearch
    cmds:
      - mkcert localhost search.derpycoder.site
      - mkdir -p certs/meilisearch
      - mv localhost+1.pem certs/meilisearch/cert.pem
      - mv localhost+1-key.pem certs/meilisearch/key.pem
  generate:imgproxy_hash:
    desc: Generates salt & key for Imgproxy
    cmds:
      - echo "salt:" `mix imgproxy.gen.secret`
      - echo "key:" `mix imgproxy.gen.secret`
  generate:docs:
    desc: Generates documentation.
    cmds:
      - mix docs

  spawn:cockroaches:
    desc: Start Cockroach DB Server & Initiate
    summary: |
      Visit: http://localhost:8081
    cmds:
      - cockroach start
        --certs-dir=certs/cockroach_db
        --store=roach-prime
        --listen-addr=localhost:26257
        --http-addr=localhost:8080
        --join=localhost:26257,localhost:26258,localhost:26259
      # - cockroach start
      #   --certs-dir=certs/cockroach_db
      #   --store=roach-alpha
      #   --listen-addr=localhost:26258
      #   --http-addr=localhost:8081
      #   --join=localhost:26257,localhost:26258,localhost:26259
      #   --background
      # - cockroach start
      #   --certs-dir=certs/cockroach_db
      #   --store=roach-beta
      #   --listen-addr=localhost:26259
      #   --http-addr=localhost:8082
      #   --join=localhost:26257,localhost:26258,localhost:26259
      #   --background
  disperse:cockroaches:
    desc: Initialize the Cockroach DB Cluster
    summary: |
      Need to be called only once!
    cmds:
      - cockroach init
        --certs-dir=certs/cockroach_db
        --host=localhost:26257

  setup:hosts:
    desc: Modifies the hostsfile, to allow development using named url and https.
    summary: |
      It allows us to use derpycoder.site or derpycoder.piv for local development.
      Run: `cat /etc/hosts` to check if the command ran successfully
      Or edit manually using `code /etc/hosts`
    cmds:
      - sudo hostsfile add
        derpycoder.site
        s3.derpycoder.site
        www.derpycoder.site
        img.derpycoder.site
        docs.derpycoder.site
        minio.derpycoder.site
        pgweb.derpycoder.site
        search.derpycoder.site
        netdata.derpycoder.site
        livebook.derpycoder.site
        cockroach.derpycoder.site
        127.0.0.1
  setup:ecto:
    desc: Runs create, migrate, initializes super admin.
    cmds:
      - mix ecto.setup
  setup:super_admin:
    desc: Initializes the first Super Admin
    summary: |
      Useful for securely setting up the first super admin, by taking the values from
      the following environment variables:
        - SUPER_ADMIN_USER_IDS
        - SUPER_ADMIN_USER_ID
        - SUPER_ADMIN_USER_NAME
        - SUPER_ADMIN_USER_EMAIL
        - SUPER_ADMIN_USER_PASSWORD
    cmds:
      - mix app.setup super_admin

  seed:ecto:
    desc: Runs the seeds file
    cmds:
      - mix ecto.seed

  start:netdata:
    desc: Start realtime system monitor
    summary: |
      http://localhost:19999
    cmds:
      - netdata
  start:caddy:
    desc: Starts Caddy
    summary: |
      Use `caddy run` for a non Daemon mode!
    cmds:
      - caddy start
  start:pgweb:
    desc: Start pgweb, to inspect the contents of the Database.
    cmds:
      - pgweb --url "postgres://derp@localhost:26257/derpy_coder_dev?sslmode=verify-ca&sslcert=certs/cockroach_db/client.derp.crt&sslkey=certs/cockroach_db/client.derp.key&sslrootcert=certs/cockroach_db/ca.crt&password=wubalubadubdub&cluster=roach-infestation"
        --listen 8000
  start:minio:
    desc: Starts MinIO
    summary: |
      Host: https://s3.derpycoder.site
      Username & Password: [derp, wubalubadubdub]

      Make Bucket:
      mc mb minio/honeycomb

      Copy file to the bucket:
      mc cp priv/static/images/phoenix.png minio/honeycomb
    cmds:
      - minio server start -address :9000 --console-address :9443 --certs-dir certs/minio
      - mc alias set minio https://s3.derpycoder.site derp wubalubadubdub
    env:
      MINIO_ROOT_USER: derp
      MINIO_ROOT_PASSWORD: wubalubadubdub
      MINIO_SERVER_URL: https://s3.derpycoder.site
      MINIO_BROWSER_REDIRECT_URL: https://minio.derpycoder.site
  start:imgproxy:
    desc: Starts Imgproxy server
    summary: |
      - Configurations: https://github.com/imgproxy/imgproxy/blob/master/docs/configuration.md
      - https://img.derpycoder.site/EsO27O7uG9o1ibaMyo2-JR1ca33mMaGkeGfQYzoBijs/rs:fit:512:64:false/czM6Ly9ob25leWNvbWIvcGhvZW5peC5wbmc.png
      - http://localhost:9080/EsO27O7uG9o1ibaMyo2-JR1ca33mMaGkeGfQYzoBijs/rs:fit:512:64:false/czM6Ly9ob25leWNvbWIvcGhvZW5peC5wbmc.png
    cmds:
      - imgproxy
    env:
      IMGPROXY_USE_S3: true
      AWS_ACCESS_KEY_ID: derp
      AWS_SECRET_ACCESS_KEY: wubalubadubdub
      IMGPROXY_S3_ENDPOINT: https://s3.derpycoder.site
      IMGPROXY_BIND: :9080
      IMGPROXY_KEY: 943dba783daf474a38beee580326cb28a90c48de7a504f23de7c8f5689d96426eccdafc3e8280c8747a82d39a332ebc14611079689d7ac1938623a909adfa273
      IMGPROXY_SALT: acd0087624cc841a557be9b82002cbcb818e2b024cbdf7e32fabd2ed22655da5724d40e729ed79e1c12c53960c400bad9a3ee7a5d1fd930887104119d83672e3
  start:varnish:
    desc: Starts Varnish Cache
    cmds:
      - sudo varnishd -s file,/tmp,100M -a 127.0.0.1:3000 -f `realpath ./varnish/varnish.vcl`
  start:meilisearch:
    desc: Starts a fast search database.
    summary: |
      http://localhost:7700
    cmds:
      - meilisearch --no-analytics --ssl-require-auth
    env:
      MEILI_MASTER_KEY: wubalubadubdub
      MEILI_ENV: development
      MEILI_SSL_CERT_PATH: certs/meilisearch/cert.pem
      MEILI_SSL_KEY_PATH: certs/meilisearch/key.pem
  start:livebook:
    desc: Stars a livebook server
    cmds:
      - livebook server
    env:
      LIVEBOOK_HOME: livebook
      LIVEBOOK_PORT: 49223
      LIVEBOOK_SHUTDOWN_ENABLED: true
      LIVEBOOK_TOKEN_ENABLED: false
      # LIVEBOOK_DEFAULT_RUNTIME: attached:derpycoder:wubalubadubdub
  start:server:
    desc: Runs the server with a custom name
    cmds:
      - elixir --sname derpycoder --cookie wubalubadubdub -S mix phx.server
  start:console:
    desc: Run iex in conjunction with the server
    summary: |
      Make sure the server is running.
      This is useful for running iex alongside server.
      Which means any PubSub events fired from iex is received by the server.
    cmds:
      - iex --sname console --cookie wubalubadubdub --remsh derpycoder
  start:iex:
    desc: Run iex standalone
    cmds:
      - iex --sname iex --cookie wubalubadubdub -S mix
  start:csql:
    desc: Starts Cockroach CLI
    summary: |
      - cockroach sql --certs-dir=certs/cockroach_db --host=localhost:26257
      - CREATE USER derp WITH PASSWORD 'wubalubadubdub';
      - GRANT admin TO derp;
      - SHOW USERS;
      - \q
    cmds:
      - cockroach sql --certs-dir=certs/cockroach_db --user=derp --host=localhost:26257

  analyze:cons:
    desc: Analyze code, using Credo, for consistency
    cmds:
      - cmd: mix credo
        ignore_error: true
  analyze:vuln:
    desc: Analyze code, using Sobelow, for vulnerabilities
    cmds:
      - cmd: mix sobelow --compact

  format:check:
    desc: Format code
    cmds:
      - mix format --check-formatted
  format:code:
    desc: Format code
    cmds:
      - mix format

  optimize:images:
    desc: Optimize All Images in Assets folder.
    cmds:
      - open -a ImageOptim ./priv/static/images
  heexify:svgs:
    desc: Convers SVGs to Heex Components.
    cmds:
      - mix app.heexify

  update:deps:
    desc: Update all dependencies
    cmds:
      - mix local.phx
      - mix local.hex
      - mix deps.update --all
      - tasks: [install:deps]

  reload:caddy:
    desc: Reloads Caddy Config
    cmds:
      - caddy reload

  locate:cockroaches:
    desc: List all the Cockroach DB instances
    cmds:
      - ps -ef | grep cockroach | grep -v grep
  terminate:cockroach:
    desc: Terminate a Cockroach DB instance
    summary: |
      task stop:cockroach -- <pid>
    cmds:
      - kill -TERM {{.CLI_ARGS}}
  exterminate:cockroaches:
    desc: Terminate all Cockroach DB instances
    summary: |
      Graceful, long command:
      for pid in $(ps -ef | grep cockroach | grep -v grep | awk '{print $2}'); do kill -SIGTERM $pid; done

      Better command: task exterminate:cockroaches
    cmds:
      - pkill -SIGTERM -f "roach-"
  eradicate:cockroaches:
    desc: Force kill all Cockroach DB instances
    cmds:
      - pkill -SIGKILL -f "roach-"
  obliviate:cockroaches:
    desc: Eradicate all Cockroaches
    summary: |
      task eradicate:cockroaches -- <roach-name>
    cmds:
      - rm -rf roach-prime {{.CLI_ARGS}}

  terminate:varnish:
    desc: Kill Varnish
    cmds:
      - sudo pkill varnish
  terminate:netdata:
    desc: Terminates the realtime monitor
    cmds:
      - pkill netdata
  terminate:caddy:
    desc: Closes the Caddy Instance
    cmds:
      - caddy stop

  reset:ecto:
    desc: Resets Ecto, by dropping, creating, migrating.
    cmds:
      - mix ecto.reset
  reset:deps:
    desc: Reset the unused dependencies
    cmds:
      - mix deps.clean --unused

  open:zsh:
    desc: Opens ZSH Path file, to add Paths
    summary: |
      Run the task and then add the following to end of the file:
      - source $(brew --prefix asdf)/libexec/asdf.sh
      - export ELIXIR_EDITOR="code --goto __FILE__:__LINE__"
    cmds:
      - code ~/.zshrc
      - code ~/.zshenv
  open:file:
    desc: Open any file from Module or Function name.
    summary: |
      task open.file -- DerpyCoder.Accounts.lock
      or
      task open.file -- DerpyCoder.Accounts
    cmds:
      - iex -S mix phx.server <<< "open {{.CLI_ARGS}}"

  build:docker:
    desc: Build a Docker Image
    cmds:
      - DOCKER_BUILDKIT=1 docker build -t derpy_coder .
  run:docker:
    desc: Run the built Docker Image
    summary: |
      Visit: localhost:3000
      P.S. Doesn't work without running database, which should be accessible inside the container!
    cmds:
      - docker run --env-file ./config/.env.prod -dp 3000:3000 derpy_coder
