---
version: "3"

tasks:
  install:asdf:
    desc: Install asdf and related plugins using brew
    cmds:
      - brew install asdf
      - asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
      - asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
      - asdf plugin-add postgres
  install:tools:
    desc: Install all tools with help of asdf
    summary: |
      It will pickup up versions from .tool-versions file and install them.
    cmds:
      - asdf install
      - mix local.hex
  install:deps:
    desc: Fetch & Compile dependencies
    cmds:
      - mix do deps.get, deps.compile

  start:postgres:
    desc: Start Postgres server
    cmds:
      - pg_ctl start

  setup:ecto:
    desc: Runs create, migrate, initializes super admin and finally seeds the database.
    cmds:
      - mix ecto.setup
  setup:super_admin:
    desc: Initializes the first Super Admin
    summary: |
      Useful for securely setting up the first super admin, by taking the values from
      the following environment variables:
        - SUPER_ADMIN_USER_IDS
        - SUPER_ADMIN_USER_ID
        - SUPER_ADMIN_USER_NAME
        - SUPER_ADMIN_USER_EMAIL
        - SUPER_ADMIN_USER_PASSWORD
    cmds:
      - mix app.setup super_admin

  seed:ecto:
    desc: Runs the seeds file
    cmds:
      - mix ecto.seed

  start:server:
    desc: Runs the server with a custom name
    cmds:
      - elixir --name derpy-coder@127.0.0.1 -S mix phx.server
  start:console:
    desc: Run iex in conjunction with the server
    summary: |
      Make sure the server is running.
      This is useful for running iex alongside server.
      Which means any PubSub events fired from iex is received by the server.
    cmds:
      - iex --name "console@127.0.0.1" --remsh "derpy-coder@127.0.0.1"
  start:iex:
    desc: Run iex standalone
    cmds:
      - iex -S mix
  start:psql:
    desc: Starts psql
    summary: |
      \du - For Listing all
      quit - To quit
    cmds:
      - psql -U postgres

  analyze:cons:
    desc: Analyze code, using Credo, for consistency
    cmds:
      - cmd: mix credo
        ignore_error: true
  analyze:vuln:
    desc: Analyze code, using Sobelow, for vulnerabilities
    cmds:
      - cmd: mix sobelow --compact

  format:check:
    desc: Format code
    cmds:
      - mix format --check-formatted
  format:code:
    desc: Format code
    cmds:
      - mix format

  optimize:images:
    desc: Optimize All Images in Assets folder.
    cmds:
      - open -a ImageOptim ./priv/static/images

  heexify:svgs:
    desc: Convers SVGs to Heex Components.
    cmds:
      - mix app.heexify

  update:deps:
    desc: Update all dependencies
    cmds:
      - mix deps.update --all
      - tasks: [install:deps]

  reset:ecto:
    desc: Resets Ecto, by dropping, creating, migrating, adding super admin and finally seeding the database.
    cmds:
      - mix ecto.reset
  reset:deps:
    desc: Reset the unused dependencies
    cmds:
      - mix deps.clean --unused

  stop:postgres:
    desc: Stop Postgres server
    cmds:
      - pg_ctl stop

  open:zsh:
    desc: Opens ZSH Path file, to add Paths
    summary: |
      Run the task and then add the following to end of the file:
      - source $(brew --prefix asdf)/libexec/asdf.sh
      - export ELIXIR_EDITOR="code --goto __FILE__:__LINE__"
    cmds:
      - code ~/.zshrc
      - code ~/.zshenv
  open:file:
    desc: Open any file from Module or Function name.
    summary: |
      task open.file -- DerpyCoder.Accounts.lock
      or
      task open.file -- DerpyCoder.Accounts
    cmds:
      - iex -S mix phx.server <<< "open {{.CLI_ARGS}}"
