defmodule DerpyCoder.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      DerpyCoder.Repo,
      DerpyCoderWeb.Telemetry,
      {Finch, name: DerpyCoder.Finch, pools: finch_pool_config()},
      {Phoenix.PubSub, name: DerpyCoder.PubSub},
      DerpyCoderWeb.Endpoint,
      # Start a worker by calling: DerpyCoder.Worker.start_link(arg)
      # {DerpyCoder.Worker, arg}
      FunWithFlags.Supervisor
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: DerpyCoder.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    DerpyCoderWeb.Endpoint.config_change(changed, removed)
    :ok
  end

  defp finch_pool_config() do
    finch_pool_config = Application.fetch_env!(:derpy_coder, DerpyCoder.Finch)
    default_pool_config = finch_pool_config[:default_pool_config]

    %{
      :default => [
        size: default_pool_config.size,
        count: default_pool_config.count
      ],
      "https://derpycoder.site" => [
        protocol: :http2,
        count: 50,
        conn_opts: [
          transport_opts: [
            timeout: 15_000,
            verify: :verify_peer,
            cacertfile: mkcert_path("/rootCA.pem"),
            keyfile: mkcert_path("/rootCA-key.pem")
          ]
        ]
      ],
      "https://s3.derpycoder.site" => [
        protocol: :http2,
        count: 50,
        conn_opts: [
          transport_opts: [
            timeout: 15_000,
            verify: :verify_peer,
            cacertfile: mkcert_path("/rootCA.pem"),
            keyfile: mkcert_path("/rootCA-key.pem")
          ]
        ]
      ]
      # "https://vendors.paddle.com" => [
      #   protocol: :http2,
      #   count: 50,
      #   conn_opts: [
      #     transport_opts: [
      #       timeout: 15_000
      #     ]
      #   ]
      # ],
      # "http://localhost:4000" => [
      #   count: 50,
      #   conn_opts: [
      #     transport_opts: [
      #       verify: :verify_none
      #     ]
      #   ]
      # ],
    }
  end

  # Gets the path of the Certificate & Keyfile generated by Mkcert
  # Useful for local development, allows usage of HTTPS in local!
  defp mkcert_path(file_name),
    do: (System.cmd("mkcert", ["-CAROOT"]) |> elem(0) |> String.trim()) <> file_name
end
